@startuml

!include ../bangun_geometri/BangunDatar.puml
package jenis_datar{
    class JajaranGenjang{
    - a: double
    - t: double
    - b: double

    + JajaranGenjang(a: double, t: double, b: double)
    + hitungLuas(): double
    + hitungKeliling(): double
    }

    bangun_geometri.BangunDatar <.. JajaranGenjang
}

@enduml