@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/Segitiga.puml

package jenis_ruang{
    class LimasSegitiga{

        + LimasSegitiga()
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. LimasSegitiga
    jenis_datar.Segitiga <-- LimasSegitiga
}

@enduml
