@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/Persegi.puml

package jenis_ruang{
    class LimasPersegi{

        + LimasPersegi()
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. LimasPersegi
    jenis_datar.Persegi <-- LimasPersegi
}

@enduml
