@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/JajaranGenjang.puml

package jenis_ruang{
    class PrismaJajaranGenjang{

        + PrismaJajaranGenjang()
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. PrismaJajaranGenjang
    jenis_datar.JajaranGenjang <-- PrismaJajaranGenjang
}

@enduml