@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/LayangLayang.puml

package jenis_ruang{
    class PrismaLayangLayang{

        + PrismaLayangLayang()
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. PrismaLayangLayang
    jenis_datar.LayangLayang <-- PrismaLayangLayang
}

@enduml