@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/Trapesium.puml

package jenis_ruang{
    class PrismaTrapesium{

        + PrismaTrapesium()
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. PrismaTrapesium
    jenis_datar.Trapesium <-- PrismaTrapesium
}

@enduml