@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/Lingkaran.puml

package jenis_ruang{
    class CincinBola{
        
        + CincinBola()
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. CincinBola
    jenis_datar.Lingkaran <-- CincinBola
}

@enduml
