@startuml
!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_ruang/Bola.puml

package jenis_ruang{
    class JuringBola {
        - sudut : double
        + JuringBola(r: double, sudut: double)
        + hitungVolume() : double
        + hitungLuasPermukaan() : double
    }

    bangun_geometri.BangunRuang <.. JuringBola
    jenis_ruang.Bola <-- JuringBola
}

@enduml
