@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/Lingkaran.puml

package jenis_ruang{
    class Kerucut{

        + Kerucut()
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. Kerucut
    jenis_datar.Lingkaran <-- Kerucut
}

@enduml
