@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/LayangLayang.puml

package jenis_ruang{
    class LimasLayangLayang{
        - h : double
        - alas : LayangLayang
        
        + LimasLayangLayang(alas : LayangLayang, h : double)
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. LimasLayangLayang
    jenis_datar.LayangLayang <-- LimasLayangLayang
}

@enduml
