@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/BelahKetupat.puml

package jenis_ruang{
    class LimasBelahKetupat{
        - h : double
        - alas : BelahKetupat

        + LimasBelahKetupat(alas : BelahKetupat, h : double)
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. LimasBelahKetupat
    jenis_datar.BelahKetupat <-- LimasBelahKetupat
}

@enduml
