@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/LayangLayang.puml

package jenis_ruang{
    class PrismaLayangLayang{
        - h : double
        - alas : LayangLayang

        + PrismaLayangLayang(alas : LayangLayang, h : double)
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. PrismaLayangLayang
    jenis_datar.LayangLayang <-- PrismaLayangLayang
}

@enduml