@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/Persegi.puml

package jenis_ruang{
    class PrismaPersegi{

        - alas : Persegi
        - tinggi : double
        + PrismaPersegi(alas : Persegi, tinggi : double)
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. PrismaPersegi
    jenis_datar.Persegi <-- PrismaPersegi
}

@enduml