@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/Lingkaran.puml

package jenis_ruang{
    class Tabung{
        - alas:lingkaran
        - h: doubel
        + Tabung(alas:lingkaran, h:doubel)
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. Tabung
    jenis_datar.Lingkaran <-- Tabung
}

@enduml