@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_ruang/Bola.puml

package jenis_ruang{
    class TemberengLingkaran{

        + TemberengLingkaran()
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }

    bangun_geometri.BangunRuang <.. TemberengLingkaran
    jenis_ruang.Bola <-- TemberengLingkaran
}

@enduml