@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_datar/Lingkaran.puml

package jenis_ruang{
    class TemberengLingkaran{

        + TemberengLingkaran()
        + hitungVolume(): double
        + hitungLuasPermukaan(): double
    }
    //haii
    bangun_geometri.BangunRuang <.. TemberengLingkaran
    jenis_datar.Lingkaran <-- TemberengLingkaran
}

@enduml