@startuml

!include ../bangun_geometri/BangunRuang.puml
!include ../jenis_ruang/Bola.puml

package jenis_ruang{
    class TemberengBola {
        - tinggi : double
        + TemberengBola(r: double, tinggi: double)
        + hitungVolume() : double
        + hitungLuasPermukaan() : double
    }
    //haiidfafsaf
    bangun_geometri.BangunRuang <.. TemberengLingkaran
    jenis_ruang.Bola <-- TemberengLingkaran
}

@enduml