@startuml

!include ../benda-geometri/BangunRuang.puml
!include ../jenis-datar/Lingkaran.puml

package jenis-ruang{
    class Kerucut{
    - tinggi: double
    - s: double

    + Kerucut(jariJari: double, tinggi: double, s: double)
    + hitungVolume(): double
    + getVolumeKerucut(): double
    + hitungLuasPermukaan(): double
    + getLuasPermukaanKerucut(): double
    }

    BangunRuang <|.. Kerucut
    Lingkaran <|-- Kerucut
}

@enduml