@startuml

!include ../benda-geometri/BangunRuang.puml
!include ../jenis-datar/LayangLayang.puml

package jenis-ruang{
    class LimasLayangLayang{
    - tinggiLimas: double
    - tSegitiga: double

    + LimasLayangLayang(diagonal1: double, diagonal2: double, sisiA: double, sisiB: double, tinggiLimas: double, tSegitiga: double)
    + hitungVolume(): double
    + getVolumeLimasLayangLayang(): double
    + hitungLuasPermukaan(): double
    + getLuasPermukaanLimasLayangLayang(): double
    }

    BangunRuang <|.. LimasLayangLayang
    LayangLayang <|-- LimasLayangLayang
}

@enduml