@startuml

!include ../benda-geometri/BangunRuang.puml
!include ../jenis-datar/JajaranGenjang.puml

package jenis-ruang{
    class LimasJajaranGenjang{
    - tinggiLimas: double
    - tSegitiga: double

    + LimasJajaranGenjang(alas: double, tinggi: double, sisiMiring: double, tinggiLimas: double, tSegitiga: double)
    + hitungVolume(): double
    + getVolumeLimasJajaranGenjang(): double
    + hitungLuasPermukaan(): double
    + getLuasPermukaanLimasJajaranGenjang(): double
    }

    BangunRuang <|.. LimasJajaranGenjang
    JajaranGenjang <|-- LimasJajaranGenjang
}

@enduml