@startuml

!include ../benda-geometri/BangunRuang.puml
!include ../jenis-datar/Segitiga.puml

package jenis-ruang{
    class LimasSegitiga{
    - tinggiLimas: double
    - tSegitiga: double

    + LimasSegitiga(alas: double, tinggi: double, sisiA: double, sisiB: double, sisiC: double, tinggiLimas: double, tSegitiga: double)
    + hitungVolume(): double
    + getVolumeLimasSegitiga(): double
    + hitungLuasPermukaan(): double
    + getLuasPermukaanLimasSegitiga(): double
    }

    BangunRuang <|.. LimasSegitiga
    Segitiga <|-- LimasSegitiga
}

@enduml