@startuml

!include ../benda-geometri/BangunRuang.puml
!include ../jenis-datar/PersegiPanjang.puml

package jenis-ruang{
    class PrismaPersegiPanjang{
    - tinggiPrisma: double

    + PrismaPersegiPanjang(panjang: double, lebar: double, tinggiPrisma: double)
    + hitungVolume(): double
    + getVolumePrismaPersegiPanjang(): double
    + hitungLuasPermukaan(): double
    + getLuasPermukaanPrismaPersegiPanjang(): double
    }

    BangunRuang <|.. PrismaPersegiPanjang
    PersegiPanjang <|-- PrismaPersegiPanjang
}

@enduml