@startuml

!include ../benda-geometri/BangunRuang.puml
!include ../jenis-datar/Trapesium.puml

package jenis-ruang{
    class PrismaTrapesium{
    - tinggiPrisma: double
    - tSegitiga: double

    + PrismaTrapesium(atas: double, bawah: double, tinggi: double, sisiC: double, sisiD: double, tinggiPrisma: double, tSegitiga: double)
    + hitungVolume(): double
    + getVolumePrismaTrapesium(): double
    + hitungLuasPermukaan(): double
    + getLuasPermukaanPrismaTrapesium(): double
    }

    BangunRuang <|.. PrismaTrapesium
    Trapesium <|-- PrismaTrapesium
}

@enduml