@startuml

!include ../benda-geometri/BangunRuang.puml
!include ../jenis-datar/BelahKetupat.puml

package jenis-ruang{
    class PrismaBelahKetupat{
    - tinggiPrisma: double

    + PrismaBelahKetupat(diagonal1: double, diagonal2: double, sisi: double, tinggiPrisma: double)
    + hitungVolume(): double
    + getVolumePrismaBelahKetupat(): double
    + hitungLuasPermukaan(): double
    + getLuasPermukaanPrismaBelahKetupat(): double
    }

    BangunRuang <|.. PrismaBelahKetupat
    BelahKetupat <|-- PrismaBelahKetupat
}

@enduml