@startuml

!include ../benda-geometri/BangunRuang.puml
!include ../jenis-datar/LayangLayang.puml

package jenis-ruang{
    class PrismaLayangLayang{
    - tinggiPrisma: double

    + PrismaLayangLayang(diagonal1: double, diagonal2: double, sisiA: double, sisiB: double, tinggiPrisma: double)
    + hitungVolume(): double
    + getVolumePrismaLayangLayang(): double
    + hitungLuasPermukaan(): double
    + getLuasPermukaanPrismaLayangLayang(): double
    }

    BangunRuang <|.. PrismaLayangLayang
    LayangLayang <|-- PrismaLayangLayang
}

@enduml