@startuml

!include ../benda-geometri/BangunRuang.puml
!include ../jenis-datar/JajaranGenjang.puml

package jenis-ruang{
    class PrismaJajaranGenjang{
    - tinggiPrisma: double

    + PrismaJajaranGenjang(alas: double, tinggi: double, sisiMiring: double, tinggiPrisma: double)
    + hitungVolume(): double
    + getVolumePrismaJajaranGenjang(): double
    + hitungLuasPermukaan(): double
    + getLuasPermukaanPrismaJajaranGenjang(): double
    }

    BangunRuang <|.. PrismaJajaranGenjang
    JajaranGenjang <|-- PrismaJajaranGenjang
}

@enduml