@startuml

!include ../benda-geometri/BangunRuang.puml
!include ../jenis-datar/Lingkaran.puml

package jenis-ruang{
    class Tabung{
    - tinggi: double

    + Tabung(jariJari: double, tinggi: double)
    + hitungVolume(): double
    + getVolumeTabung(): double
    + hitungLuasPermukaan(): double
    + getLuasPermukaanTabung(): double
    }

    BangunRuang <|.. Tabung
    Lingkaran <|-- Tabung
}

@enduml