@startuml

top to bottom direction

!include ../bangun_geometri/BangunDatar.puml
!include ../bangun_geometri/BangunRuang.puml

!include ../jenis_datar/BelahKetupat.puml
!include ../jenis_datar/JajaranGenjang.puml
!include ../jenis_datar/JuringLingkaran.puml
!include ../jenis_datar/LayangLayang.puml
!include ../jenis_datar/Lingkaran.puml
!include ../jenis_datar/Persegi.puml
!include ../jenis_datar/PersegiPanjang.puml
!include ../jenis_datar/Segitiga.puml
!include ../jenis_datar/TemberengLingkaran.puml
!include ../jenis_datar/Trapesium.puml

!include ../jenis_ruang/Bola.puml
!include ../jenis_ruang/CincinBola.puml
!include ../jenis_ruang/JuringBola.puml
!include ../jenis_ruang/Kerucut.puml
!include ../jenis_ruang/KerucutTerpancung.puml
!include ../jenis_ruang/LimasBelahKetupat.puml
!include ../jenis_ruang/LimasJajaranGenjang.puml
!include ../jenis_ruang/LimasLayangLayang.puml
!include ../jenis_ruang/LimasPersegi.puml
!include ../jenis_ruang/LimasPersegiPanjang.puml
!include ../jenis_ruang/LimasSegitiga.puml
!include ../jenis_ruang/LimasTrapesium.puml
!include ../jenis_ruang/PrismaBelahKetupat.puml
!include ../jenis_ruang/PrismaJajaranGenjang.puml
!include ../jenis_ruang/PrismaLayangLayang.puml
!include ../jenis_ruang/PrismaPersegi.puml
!include ../jenis_ruang/PrismaPersegiPanjang.puml
!include ../jenis_ruang/PrismaSegitiga.puml
!include ../jenis_ruang/PrismaTrapesium.puml
!include ../jenis_ruang/Tabung.puml
!include ../jenis_ruang/TemberengBola.puml

@enduml