@startuml

!include ../bangun_geometri/BangunDatar.puml

package jenis_datar{
    class LayangLayang{
    - d1: double
    - d2: double
    - a: double
    - b: double

    + LayangLayang(d1: double, d2: double, a: double, b:double)
    + hitungLuas(): double
    + hitungKeliling(): double
    }
    
    bangun_geometri.BangunDatar <.. LayangLayang
}

@enduml
