@startuml

!include ../bangun_geometri/BangunDatar.puml
package jenis_datar{
    class Persegi{
    - s: double

    + Persegi(s: double)
    + hitungLuas(): double
    + hitungKeliling(): double
    }
    //dddd
    bangun_geometri.BangunDatar <.. Persegi
}

@enduml
