@startuml

!include ../bangun_geometri/BangunDatar.puml
package jenis_datar{
    class Segitiga{
    - a: double
    - t: double

    + Segitiga(a: double, t: double)
    + hitungLuas(): double
    + hitungKeliling(): double
    }
    //fu gay
    bangun_geometri.BangunDatar <.. Segitiga
}

@enduml
