@startuml

!include ../bangun_geometri/BangunDatar.puml
package jenis_datar{
    class Trapesium{
    - a: double
    - b: double
    - c: double
    - t: double

    + BelahKetupat(a: double, b: double, c: double, t: double)
    + hitungLuas(): double
    + hitungKeliling(): double
    }

    bangun_geometri.BangunDatar <.. Trapesium
}

@enduml
