@startuml

!include ../benda-geometri/BangunDatar.puml

package jenis-datar{
    class LayangLayang{
    - diagonal1: double
    - diagonal2: double
    - sisiA: double
    - sisiB: double

    + LayangLayang(diagonal1: double, diagonal2: double, sisiA: double, sisiB: double)
    + hitungLuas(): double
    + getLuasLayangLayang(): double
    + hitungKeliling(): double
    + getKelilingLayangLayang(): double
    }

    BangunDatar <|.. LayangLayang
}

@enduml