@startuml

!include ../benda-geometri/BangunDatar.puml

package jenis-datar{
    class Lingkaran{
    - jariJari: double

    + Lingkaran(jariJari: double)
    + hitungLuas(): double
    + getLuasLingkaran(): double
    + hitungKeliling(): double
    + getKelilingLingkaran(): double
    }

    BangunDatar <|.. Lingkaran
}

@enduml