@startuml

!include ../benda-geometri/BangunDatar.puml

package jenis-datar{
    class PersegiPanjang{
    - panjang: double
    - lebar: double

    + PersegiPanjang(panjang: double, lebar: double)
    + hitungLuas(): double
    + getLuasPersegiPanjang(): double
    + hitungKeliling(): double
    + getKelilingPersegiPanjang(): double
    }

    BangunDatar <|.. PersegiPanjang
}

@enduml