@startuml

!include ../benda-geometri/BangunDatar.puml

package jenis-datar{
    class Persegi{
    - sisi: double

    + Persegi(sisi: double)
    + hitungLuas(): double
    + getLuasPersegi(): double
    + hitungKeliling(): double
    + getKelilingPersegi(): double
    }

    BangunDatar <|.. Persegi
}

@enduml