@startuml

!include ../benda-geometri/BangunDatar.puml

package jenis-datar{
    class Segitiga{
    - alas: double
    - tinggi: double
    - sisiA: double
    - sisiB: double
    - sisiC: double

    + Segitiga(alas: double, tinggi: double, sisiA: double, sisiB: double, sisiC: double)
    + hitungLuas(): double
    + getLuasSegitiga(): double
    + hitungKeliling(): double
    + getKelilingSegitiga(): double
    }

    BangunDatar <|.. Segitiga
}

@enduml