@startuml

!include ../jenis-datar/JuringLingkaran.puml

package jenis-datar{
    class TemberengLingkaran{
    - taliBusur: double

    + TemberengLingkaran(jariJari: double, sudut: double, taliBusur: double)
    + hitungLuas(): double
    + getLuasTemberengLingkaran(): double
    + hitungKeliling(): double
    + getKelilingTemberengLingkaran(): double
    }

    JuringLingkaran <|-- TemberengLingkaran
}

@enduml