@startuml

!include ../benda-geometri/BangunDatar.puml

package jenis-datar{
    class Trapesium{
    - atas: double
    - bawah: double
    - tinggi: double
    - sisiC: double
    - sisiD: double

    + Trapesium(atas: double, bawah: double, tinggi: double, sisiC: double, sisiD: double)
    + hitungLuas(): double
    + getLuasTrapesium(): double
    + hitungKeliling(): double
    + getKelilingTrapesium(): double
    }

    BangunDatar <|.. Trapesium
}

@enduml